"""empty message

Revision ID: 9e73014ecd31
Revises: f304e870cc06
Create Date: 2017-08-25 19:02:22.807449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e73014ecd31'
down_revision = 'f304e870cc06'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('realname', sa.String(length=30), nullable=False))
    op.add_column('teachers', sa.Column('realname', sa.String(length=30), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teachers', 'realname')
    op.drop_column('students', 'realname')
    ### end Alembic commands ###
