"""empty message

Revision ID: f304e870cc06
Revises: 
Create Date: 2017-08-23 15:52:32.204738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f304e870cc06'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('containers',
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('students',
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('isTeacher', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('teachers',
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('isTeacher', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('courses',
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('teacherName', sa.String(length=60), nullable=True),
    sa.Column('courseNums', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['teacherName'], ['teachers.name'], ),
    sa.PrimaryKeyConstraint('name'),
    sa.UniqueConstraint('courseNums')
    )
    op.create_table('experiments',
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('content', sa.LargeBinary(), nullable=True),
    sa.Column('courseName', sa.String(length=60), nullable=True),
    sa.Column('containerName', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['courseName'], ['courses.name'], ),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('registrations',
    sa.Column('studentName', sa.String(length=60), nullable=True),
    sa.Column('courseName', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['courseName'], ['courses.name'], ),
    sa.ForeignKeyConstraint(['studentName'], ['students.name'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registrations')
    op.drop_table('experiments')
    op.drop_table('courses')
    op.drop_table('teachers')
    op.drop_table('students')
    op.drop_table('containers')
    # ### end Alembic commands ###
